name: docs

on:
  # æ¯å½“ push åˆ° main åˆ†æ”¯æ—¶è§¦å‘éƒ¨ç½²
  push:
    branches: [main, master]
  # æ‰‹åŠ¨è§¦å‘éƒ¨ç½²
  workflow_dispatch:

# ğŸ‘‡ å¿…é¡»æ·»åŠ ï¼å®˜æ–¹éƒ¨ç½²éœ€è¦è¿™äº›æƒé™
permissions:
  contents: read # è¯»å–ä»£ç 
  pages: write # éƒ¨ç½²åˆ° Pages
  id-token: write # ç”¨äºå®‰å…¨è®¤è¯

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          # â€œæœ€è¿‘æ›´æ–°æ—¶é—´â€ ç­‰ git æ—¥å¿—ç›¸å…³ä¿¡æ¯ï¼Œéœ€è¦æ‹‰å–å…¨éƒ¨æäº¤è®°å½•
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          # é€‰æ‹©è¦ä½¿ç”¨çš„ pnpm ç‰ˆæœ¬
          # version: 10
          # ä½¿ç”¨ pnpm å®‰è£…ä¾èµ–
          run_install: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          # é€‰æ‹©è¦ä½¿ç”¨çš„ node ç‰ˆæœ¬
          node-version: 22
          # ç¼“å­˜ pnpm ä¾èµ–
          cache: pnpm

      # è¿è¡Œæ„å»ºè„šæœ¬
      - name: Build VuePress site
        run: pnpm docs:build

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          path: docs/.vuepress/dist # VuePress é»˜è®¤æ„å»ºè¾“å‡ºç›®å½•
